# Generated by Django 2.1.2 on 2018-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('host_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('states', models.CharField(max_length=50)),
                ('hava_user_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('log_context', models.CharField(max_length=1000)),
                ('hava_submit_log_name', models.CharField(default='', max_length=50)),
                ('hava_submit_log_pid', models.CharField(default='', max_length=50)),
                ('states', models.CharField(default='', max_length=50)),
                ('step', models.CharField(default='', max_length=10)),
                ('gmt_create', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hava_node', models.CharField(max_length=100)),
                ('hava_user_group', models.CharField(max_length=100)),
                ('hava_config', models.CharField(max_length=100)),
                ('gmt_create', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
