# Generated by Django 2.1.2 on 2018-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('log_context', models.CharField(max_length=1000)),
                ('gmt_create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remote_ip', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
                ('permission', models.CharField(max_length=100)),
                ('config', models.CharField(max_length=100)),
                ('gmt_create', models.DateTimeField()),
            ],
        ),
    ]
