# Generated by Django 2.1.2 on 2018-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitinfo',
            name='host_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
