# Generated by Django 2.1.2 on 2018-11-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitinfo',
            old_name='config',
            new_name='hava_config',
        ),
        migrations.RenameField(
            model_name='submitinfo',
            old_name='node',
            new_name='hava_node',
        ),
        migrations.RenameField(
            model_name='submitinfo',
            old_name='permission',
            new_name='hava_user_group',
        ),
        migrations.RenameField(
            model_name='submitinfo',
            old_name='remote_ip',
            new_name='ip',
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='gmt_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submitinfo',
            name='gmt_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
