# Generated by Django 2.1.2 on 2018-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0002_submitinfo_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
