# Generated by Django 2.1.2 on 2018-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0002_auto_20181115_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='hava_submit_log_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='hava_submit_log_pid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='states',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='step',
            field=models.CharField(default='', max_length=10),
        ),
    ]
