# Generated by Django 2.1.2 on 2018-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0004_loginfo_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='record_content', max_length=32)),
            ],
            options={
                'db_table': 'record_001',
            },
        ),
    ]
