# Generated by Django 2.1.2 on 2018-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0006_auto_20181202_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitinfo',
            name='approve_states',
            field=models.CharField(default='', max_length=50),
        ),
    ]
