# Generated by Django 2.1.2 on 2018-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havaApp', '0007_submitinfo_approve_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='approve_states',
            field=models.CharField(default='', max_length=50),
        ),
    ]
